### ISSUE TITLE
Privacy pass editorial comments 

### ISSUE THREAD

**Issue by jsalowey** [ietf-wg-privacypass/base-drafts#203]
- [x] 1. The Reference PPEXT is not cited in the document. seems it could be sited in the into PR #200 
- [x] 2. I think it would be good to explicitly say that the HTTP authentication protocol is  targeted at redemption and the issuer protocol is targeted at issuance.  PR #201
- [ ] 3. Last paragraph in section 3.2.1 mentions Origin Allow Lists.   These allow lists are not specifically mentioned earlier in the document.  Can you clarify this.  
- [ ] 4. In section 4.3 and 4.4 is the attester involved in the TokeRequest and TokenResponse messages?  Is the attester proxying the communication? It would be good to clarify this in the text. 
- [ ] 5. Section 6 has an incomplete reference. 
- [x] 6. It seems that the Reference to RFC 8446 is not needed. PR #202
- [ ] 7. The link - https://research.fb.com/wp-content/uploads/2021/01/PrivateStats-De-Identified-Authenticated-Logging-at-Scale_final.pdf does not work perhaps this is the updated one? - https://research.fb.com/privatestats
